version: "3"

services:
  web:
    container_name: node-app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: node-db-app
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    # logging:
    #   driver: none
    